name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: "14.x"
            registry-url: "https://npm.pkg.github.com/"
            scope: "@play-co"
      - run: npm install
        env:
            NODE_AUTH_TOKEN: ${{ secrets.PLAYCO_PACKAGES_TOKEN }}
      - run: npm run lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PLAYCO_PACKAGES_TOKEN }}
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PLAYCO_PACKAGES_TOKEN }}
      - run: npm test
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PLAYCO_PACKAGES_TOKEN }}
